apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  namespace: ingestion-environment-namespace
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
