nameOverride: ""
fullnameOverride: ""

image:
  repository: vernemq/vernemq
  tag: 2.1.1
  pullPolicy: IfNotPresent

replicaCount: 1

additionalEnv:
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "off"
  - name: DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL
    value: "warning"
  - name: DOCKER_VERNEMQ_SYSTREE_ENABLED
    value: "off"
  - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
    value: "4"

  # Enable plugins
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY
    value: "on"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
    value: "off"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
    value: "off"

  # Authentication with Redis
  - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED
    value: "on"
  - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST
    value: "redis"
  - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT
    value: "6379"
  - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__DATABASE
    value: "0"
  - name: DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-auth
        key: REDIS_PASSWORD

  # Parâmetros para melhorar performance
  - name: DOCKER_VERNEMQ_LISTENER__TCP__NR_OF_ACCEPTORS
    value: "40"
  - name: DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS
    value: "20000"
  - name: DOCKER_VERNEMQ_COORDINATE_REGISTRATIONS
    value: "off"
  - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
    value: "10"
  - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
    value: "1000"
  - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
    value: "0"
  - name: DOCKER_VERNEMQ_ERLANG__ASYNC_THREADS
    value: "128"
  - name: DOCKER_VERNEMQ_ERLANG__MAX_PORTS
    value: "1048576"

  # Facilitar PoC em netsplit
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"

envFrom: [{ secretRef: { name: redis-auth } }]

service:
  enabled: true
  type: "NodePort"
  mqtt:
    enabled: true
    port: 1883
    nodePort: 31883
  mqtts:
    enabled: false
    port: 8883
    nodePort: 31888
  ws:
    enabled: false
    port: 8080
    nodePort: 32080  
  wss:
    enabled: false
    port: 8443
    nodePort: 32084

ingress:
  enabled: false
  annotations: {}
  hosts: []
  paths: ["/"]
  tls: []

persistentVolume:
  enabled: false
  size: 5Gi
  accessModes: ["ReadWriteOnce"]
  annotations: {}

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
nodeSelector: {}
  # vernemq-dedicated: "true"
tolerations: {}
  # - key: "vernemq-dedicated"
  #   operator: "Equal"
  #   value: "true"
  #   effect: "NoSchedule"
podAntiAffinity: soft

securityContext:
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000

rbac:
  create: true
  serviceAccount:
    create: true

statefulset:
  podAnnotations: {}
  annotations: {}
  labels: {}
  lifecycle: {}
  podManagementPolicy: OrderedReady
  updateStrategy: RollingUpdate
  terminationGracePeriodSeconds: 60
  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

secretMounts: []
extraVolumes: []
extraVolumeMounts: []

pdb:
  enabled: false
  minAvailable: 1

serviceMonitor:
  create: false
  labels: {}

global:
  cattle:
    clusterId: c-m-sqk55kdr
    clusterName: cloud-architecture-validation
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemProjectId: p-hmqtg
    url: https://rancher.172-104-5-78.sslip.io  