## Sobe stack docker-compose (VerneMQ + Kafka + Collector)
compose-up:
	docker compose up -d --build

## Derruba stack docker-compose
compose-down:
	docker compose down -v

compose-logs:
	docker compose logs -f --tail=100

compose-logs-app:
	docker compose logs -f --tail=100 collector