apiVersion: v1
kind: ConfigMap
metadata:
  name: real-time-loader-config
  namespace: ingestion-environment-namespace
  labels:
    app: real-time-loader
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_GROUP_ID: "real-time-loader"
  KAFKA_READER_TOPIC: "enriched-events-topic"
  KAFKA_TOPIC_PARTITIONS: "2"
  KAFKA_RETENTION_MS: "86400000"
  KAFKA_COMPRESSION: "snappy"
  KAFKA_REPLICATION_FACTOR: "1"              # ajuste para 2 ou 3 em prod
  KAFKA_ACK_BATCH_SIZE: "1000"

  KAFKA_READER_MIN_BYTES: "262144"           # 256KB
  KAFKA_READER_MAX_BYTES: "5242880"          # 5MB
  KAFKA_READER_MAX_WAIT_MS: "150"
  KAFKA_READER_QUEUE_CAPACITY: "20000"
  KAFKA_READER_READ_LAG_INTERVAL_MS: "-1"    # desabilitado
  KAFKA_READER_SESSION_TIMEOUT_MS: "30000"
  KAFKA_READER_HEARTBEAT_INTERVAL_MS: "10000"
  KAFKA_READER_REBALANCE_TIMEOUT_MS: "60000"
  KAFKA_READER_READ_BACKOFF_MIN_MS: "100"
  KAFKA_READER_READ_BACKOFF_MAX_MS: "1000"

  PROCESSING_WORKERS: "2"

  INFLUX_URL: "http://influxdb:8086"
  INFLUX_ORG: "hems"
  INFLUX_BUCKET: "hems_timeseries"
  INFLUX_BATCH_SIZE: "5000"
  INFLUX_FLUSH_INTERVAL_MS: "100"