apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
  namespace: ingestion-environment-namespace
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_GROUP_ID: "validator"

  KAFKA_READER_TOPIC: "raw-events-topic"
  KAFKA_WRITER_TOPIC: "validated-events-topic"
  KAFKA_DLQ_TOPIC: "validated-events-dlq"

  KAFKA_TOPIC_PARTITIONS: "6"
  KAFKA_DLQ_PARTITIONS: "1"
  KAFKA_RETENTION_MS: "86400000"
  KAFKA_COMPRESSION: "snappy"
  KAFKA_REPLICATION_FACTOR: "1"
  KAFKA_ACK_BATCH_SIZE: "1000"

  KAFKA_WRITER_BATCH_SIZE: "5000"
  KAFKA_WRITER_BATCH_BYTES: "4194304"          # 4MB
  KAFKA_WRITER_BATCH_TIMEOUT_MS: "25"
  KAFKA_WRITER_REQUIRED_ACKS: "one"
  KAFKA_WRITER_MAX_ATTEMPTS: "10"

  KAFKA_READER_MIN_BYTES: "262144"             # 256KB
  KAFKA_READER_MAX_BYTES: "5242880"            # 5MB
  KAFKA_READER_MAX_WAIT_MS: "150"
  KAFKA_READER_QUEUE_CAPACITY: "20000"
  KAFKA_READER_READ_LAG_INTERVAL_MS: "-1"      # desabilitado
  KAFKA_READER_SESSION_TIMEOUT_MS: "30000"
  KAFKA_READER_HEARTBEAT_INTERVAL_MS: "10000"
  KAFKA_READER_REBALANCE_TIMEOUT_MS: "60000"
  KAFKA_READER_READ_BACKOFF_MIN_MS: "100"
  KAFKA_READER_READ_BACKOFF_MAX_MS: "1000"

  PROCESSING_WORKERS: "4"

  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  REDIS_NAMESPACE: "schema"
  REDIS_USE_PUBSUB: "true"
  REDIS_INVALIDATE_CHANNEL: "schemas:invalidate"
